// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626125428_addingnewcoulmningamayastable")]
    partial class addingnewcoulmningamayastable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Model.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkExpenseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldAmount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldCategory");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("fldExpenseDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldName");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fldUserId");

                    b.Property<int>("WeekBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("fldWeekBudgetId");

                    b.HasKey("ExpenseId");

                    b.HasIndex("WeekBudgetId");

                    b.HasIndex("UserId", "ExpenseDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("DAL.Model.Gameya", b =>
                {
                    b.Property<int>("GameyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkGameyaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameyaId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldCreatedBy");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fldIsActive");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldMonthlyContribution");

                    b.Property<int>("MyTurn")
                        .HasColumnType("int")
                        .HasColumnName("fldMyTurn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldName");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("fldStartDate");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int")
                        .HasColumnName("fldTotalMembers");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("GameyaId");

                    b.HasIndex("UserId");

                    b.ToTable("Gameyas");
                });

            modelBuilder.Entity("DAL.Model.GameyaPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fldPaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("GameyaId")
                        .HasColumnType("int")
                        .HasColumnName("fkGameyaId");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int")
                        .HasColumnName("fldMonthNumber");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("fldPaidOn");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldType");

                    b.HasKey("PaymentId");

                    b.HasIndex("GameyaId");

                    b.ToTable("GameyaPayments");
                });

            modelBuilder.Entity("DAL.Model.Installment", b =>
                {
                    b.Property<int>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkInstallmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fldIsActive");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldMonthlyAmount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldName");

                    b.Property<int>("PaidMonths")
                        .HasColumnType("int")
                        .HasColumnName("fldPaidMonths");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("fldStartDate");

                    b.Property<int>("TotalMonths")
                        .HasColumnType("int")
                        .HasColumnName("fldTotalMonths");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("InstallmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("DAL.Model.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("fldAction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fldCreatedAt");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldObjectId");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldObjectType");

                    b.Property<string>("OldStateJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldOldStateJson");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DAL.Model.MonthlySnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fldSnapshotId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<decimal>("AllocatedToWishlist")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldAllocatedToWishlist");

                    b.Property<decimal>("Bonuses")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldBonuses");

                    b.Property<decimal>("CarryOver")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldCarryOver");

                    b.Property<decimal>("CarryOverGoal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldCarryOverGoal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fldCreatedAt");

                    b.Property<decimal?>("CustomWeeklyBudget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldCustomWeeklyBudget");

                    b.Property<decimal>("FreeCash")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldFreeCash");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("fldMonth");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldSalary");

                    b.Property<decimal>("TotalCommitments")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldTotalCommitments");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.Property<decimal>("WeeklyBudget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldWeeklyBudget");

                    b.Property<decimal?>("WishlistPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldWishlistPercentage");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("fldYear");

                    b.HasKey("SnapshotId");

                    b.HasIndex("UserId", "Year", "Month");

                    b.ToTable("MonthlySnapshots");
                });

            modelBuilder.Entity("DAL.Model.SnapshotTrigger", b =>
                {
                    b.Property<int>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fldTriggerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriggerId"));

                    b.Property<decimal?>("CashInHand")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldCashInHand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fldCreatedAt");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldNote");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int")
                        .HasColumnName("fkSnapshotId");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldTriggerType");

                    b.HasKey("TriggerId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("SnapshotTriggers");
                });

            modelBuilder.Entity("DAL.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("fldAccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldConcurrencyStamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldEmail");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("fldEmailConfirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fldFullName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fldIsActive");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("fldLockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fldLockoutEnd");

                    b.Property<bool>("NewUser")
                        .HasColumnType("bit")
                        .HasColumnName("fldNewUser");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldNormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldNormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldPasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldPhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("fldPhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldSecurityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("fldTwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldUserName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[fldNormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b7e10136-59d9-4908-8546-264213377dd9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0ceb9b20-0459-48aa-b029-5c3b607e6f3d",
                            Email = "admin@MoneyFollow.com",
                            EmailConfirmed = false,
                            FullName = "Admin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NewUser = false,
                            NormalizedEmail = "ADMIN@MONEYFOLLOW.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFctG6LS8KiYEVdI0doV499jipmFK/3jNgFVjDcPHTor8FuU9BswnPGKzXHt2gLaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0214b3b3-de1e-4dc2-bd93-c20737a0191e",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DAL.Model.WeeklyBudget", b =>
                {
                    b.Property<int>("WeekBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fldWeekBudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekBudgetId"));

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldBudgetAmount");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int")
                        .HasColumnName("fkSnapshotId");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("fldWeekEnd");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int")
                        .HasColumnName("fldWeekNumber");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("fldWeekStart");

                    b.HasKey("WeekBudgetId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("WeeklyBudgets");
                });

            modelBuilder.Entity("DAL.Model.WishlistItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fldItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("fldDueDate");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("bit")
                        .HasColumnName("fldIsAchieved");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit")
                        .HasColumnName("fldIsCritical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldName");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("fldPriority");

                    b.Property<decimal>("SavePercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldSavePercentage");

                    b.Property<decimal>("SavedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldSavedAmount");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fldTargetAmount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("ItemId");

                    b.HasIndex("UserId", "Priority");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldConcurrencyStamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldName");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fldNormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[fldNormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldClaimType");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkRoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldClaimType");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkLoginProvider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkProviderKey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("fkUserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkUserId");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkRoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b7e10136-59d9-4908-8546-264213377dd9",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkUserId");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkLoginProvider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pkName");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldValue");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Model.Expense", b =>
                {
                    b.HasOne("DAL.Model.WeeklyBudget", "WeeklyBudget")
                        .WithMany("Expenses")
                        .HasForeignKey("WeekBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyBudget");
                });

            modelBuilder.Entity("DAL.Model.Gameya", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany("Gameyas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Model.GameyaPayment", b =>
                {
                    b.HasOne("DAL.Model.Gameya", "Gameya")
                        .WithMany("Payments")
                        .HasForeignKey("GameyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gameya");
                });

            modelBuilder.Entity("DAL.Model.Installment", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany("Installments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Model.Logs", b =>
                {
                    b.HasOne("DAL.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Model.MonthlySnapshot", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Model.SnapshotTrigger", b =>
                {
                    b.HasOne("DAL.Model.MonthlySnapshot", "Snapshot")
                        .WithMany("Triggers")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DAL.Model.WeeklyBudget", b =>
                {
                    b.HasOne("DAL.Model.MonthlySnapshot", "Snapshot")
                        .WithMany("WeeklyBudgets")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DAL.Model.WishlistItem", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Model.Gameya", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DAL.Model.MonthlySnapshot", b =>
                {
                    b.Navigation("Triggers");

                    b.Navigation("WeeklyBudgets");
                });

            modelBuilder.Entity("DAL.Model.User", b =>
                {
                    b.Navigation("Gameyas");

                    b.Navigation("Installments");

                    b.Navigation("MonthlySnapshots");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("DAL.Model.WeeklyBudget", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
